framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    
    annotations: false
    handle_all_throwables: true
    enabled_locales: ['en', 'fr']

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    php_errors:
        log: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: "%env(SESSION_TTL)%"
        gc_maxlifetime: "%env(SESSION_TTL)%"

    property_info:
        enabled: false
        with_constructor_extractor: false

when@dev:
    framework:
        test: true
        session:
            handler_id: ~

when@test:
    framework:
        test: true
        session:
            handler_id: ~
            storage_factory_id: session.storage.factory.mock_file
