knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: app_web_connect_google_check
            redirect_params: {}

        # https://developer.amazon.com/docs/login-with-amazon/documentation-overview.html
        amazon:
            type: amazon
            client_id: '%env(OAUTH_AMAZON_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AMAZON_CLIENT_SECRET)%'
            redirect_route: app_web_connect_amazon_check
            redirect_params: {}
        
        # https://discord.com/developers/docs/topics/oauth2
        discord:
            type: discord
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            redirect_route: app_web_connect_discord_check
            redirect_params: {}
        
        # https://developers.facebook.com/docs/facebook-login
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_CLIENT_SECRET)%'
            redirect_route: app_web_connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12
        