twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        pokemonIconUrl: '%env(POKEMON_ICON_URL)%'
        pokemonImageUrl: '%env(POKEMON_IMAGE_URL)%'
        pokemonTypeIconUrl: '%env(POKEMON_TYPE_ICON_URL)%'
        dexBannerUrl: '%env(DEX_BANNER_URL)%'

when@test:
    twig:
        strict_variables: true
