name: Pokénini

services:

  adminer:
    image: adminer:5.3.0
    ports:
      - '127.0.0.1:8082:8080'
    restart: always

  apache:
    image: httpd:2.4
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/apache/ssl:/usr/local/apache2/ssl/
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'

  api.int.moco:
    build:
      context: docker/moco/Api/int
      args:
        MOCO_VERSION: 1.5.0
    volumes:
      - ./tests/resources/moco/Api:/var/moco:ro

  api.test.moco:
    build:
      context: docker/moco/Api/test
      args:
        MOCO_VERSION: 1.5.0
    volumes:
      - ./tests/resources/moco/Api:/var/moco:ro

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: php_dev
    volumes:
      - .:/var/www/html
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1
    expose:
      - '9000'
    tty: true

  redis:
    image: redis:8.0-alpine
    volumes:
      - redis_data:/data
    command: redis-server --requirepass douze
    restart: always

  web.dev.moco:
    build:
      context: docker/moco/Web/dev
      args:
        MOCO_VERSION: 1.5.0
    volumes:
      - ./tests/resources/moco/Web/:/var/moco:ro

  web.test.moco:
    build:
      context: docker/moco/Web/test
      args:
        MOCO_VERSION: 1.5.0
    volumes:
      - ./tests/resources/moco/Web/:/var/moco:ro

volumes:
  ###> doctrine/doctrine-bundle ###
  db_data:
  db_data_test: 
  ###< doctrine/doctrine-bundle ###

  redis_data:


