name: Docker Compose Pull Up And Check
description: Use to docker compose pull and up then checks if services are correctly running
author: Renaud Douze
runs:
  using: "composite"
  steps:
    - name: Copy .env file
      shell: bash
      run: cp .env.ci .env

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Buildx Bake
      uses: docker/bake-action@v2
      with:
        load: true
        set: |
          *.cache-to=type=gha,mode=max                                                                                
          *.cache-from=type=gha 
      
    - name: Pull images
      shell: bash
      run: docker compose pull --ignore-pull-failures || true

    - name: Start services
      shell: bash
      run: docker compose --verbose up --build --wait

    - name: Composer install
      shell: bash
      run: docker compose exec -T php composer install --prefer-dist --no-progress --no-interaction

    - name: Create test database
      shell: bash
      run: |
        docker compose exec -T php bin/console -e test doctrine:database:create --if-not-exists
        docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

    - name: Doctrine Schema Validator
      shell: bash
      run: docker compose exec -T php bin/console doctrine:schema:validate --skip-sync
