controllers:
    resource:
        path: ../src/Web/Controller/
        namespace: App\Web\Controller
    type: attribute
    prefix: /{_locale}
    trailing_slash_on_root: false
    requirements:
        _locale: 'en|fr'

api_controllers:
    resource:
        path: ../src/Api/Controller/
        namespace: App\Api\Controller
    type: attribute
    trailing_slash_on_root: false
    prefix: '/api'

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_web_home_index
        permanent: true