services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $spreadsheetId: '%env(SPREADSHEET_ID)%'
            string $googleApiSheetsUrl: '%env(GOOGLE_API_SHEETS_URL)%'
            string $appApiUrl: '%env(APP_API_URL)%'
            string $listAdmin: '%env(LIST_ADMIN)%'
            string $listTrainer: '%env(LIST_TRAINER)%'
            string $listCollector: '%env(LIST_COLLECTOR)%'
            string $apiLogin: '%env(API_LOGIN)%'
            string $apiPassword: '%env(API_PASSWORD)%'
            string $demoUserId: '%env(DEMO_USER_ID)%'
            int $eloKFactor: '%env(ELO_K_FACTOR)%'
            int $eloDDifference: '%env(ELO_D_DIFFERENCE)%'
            int $eloDefault: '%env(ELO_DEFAULT)%'
            int $topCount: '%env(ELECTION_TOP_COUNT)%'
            int $electionCandidateCount: '%env(ELECTION_CANDIDATE_COUNT)%'
            
    App\Api\:
        resource: '../src/Api/'
        exclude:
            - '../src/Api/DependencyInjection/'
            - '../src/Api/Entity/'
            - '../src/Api/Kernel.php'

    App\Web\:
        resource: '../src/Web/'
        exclude:
            - '../src/Web/DependencyInjection/'
            - '../src/Web/Entity/'
            - '../src/Web/Kernel.php'

