name: CI

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  composer-audit:
    name: Security / Composer Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer audit

  symfonycorp-security-checker:
    name: Security / SymfonyCorp Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
            path: ~/.symfony/cache
            key: db
      - uses: symfonycorp/security-checker-action@v5
  
  phpcsfixer:
    name: Security / PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
        with:
          args: check

  dependency-check:
    name: Security / OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.5/dependency-check-7.0.5-release.zip
          unzip dependency-check-7.0.5-release.zip
      - name: Run Dependency-Check
        run: ./dependency-check/bin/dependency-check.sh --project "mon-projet" --scan . --format "HTML" --out ./dependency-check-report.html
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: ./dependency-check-report.html