name: Security

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  composer-audit:
    name: Composer Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: composer audit

  symfonycorp-security-checker:
    name: SymfonyCorp Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-db
        with:
            path: ~/.symfony/cache
            key: db
      - uses: symfonycorp/security-checker-action@v5
